apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-beat
  labels:
    app: debtflow
    component: beat
spec:
  replicas: {{ .Values.replicaCount.beat }}
  selector:
    matchLabels:
      app: debtflow
      component: beat
  template:
    metadata:
      labels:
        app: debtflow
        component: beat
    spec:
      serviceAccountName: {{ .Release.Name }}-worker
      containers:
        - name: beat
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          command: ["celery", "-A", "config.celery", "beat", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            {{- toYaml .Values.resources.beat | nindent 12 }}
