apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: debtflow
    component: api
  annotations:
    {{- toYaml .Values.serviceAccount.api.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: debtflow
    component: worker
  annotations:
    {{- toYaml .Values.serviceAccount.worker.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: debtflow
    component: frontend
