apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: debtflow
    component: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app: debtflow
      component: worker
  template:
    metadata:
      labels:
        app: debtflow
        component: worker
    spec:
      serviceAccountName: {{ .Release.Name }}-worker
      containers:
        - name: worker
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          command: ["celery", "-A", "config.celery", "worker", "--loglevel=info", "--concurrency={{ .Values.celery.concurrency }}"]
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
